# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = ~/ClionProjects/Quadro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = ~/ClionProjects/Quadro/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start ~/ClionProjects/Quadro/cmake-build-debug/CMakeFiles ~/ClionProjects/Quadro/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start ~/ClionProjects/Quadro/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Quadro

# Build rule for target.
Quadro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Quadro
.PHONY : Quadro

# fast build rule for target.
Quadro/fast:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/build
.PHONY : Quadro/fast

lib/Timer/Timer.o: lib/Timer/Timer.cpp.o

.PHONY : lib/Timer/Timer.o

# target to build an object file
lib/Timer/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/Timer/Timer.cpp.o
.PHONY : lib/Timer/Timer.cpp.o

lib/Timer/Timer.i: lib/Timer/Timer.cpp.i

.PHONY : lib/Timer/Timer.i

# target to preprocess a source file
lib/Timer/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/Timer/Timer.cpp.i
.PHONY : lib/Timer/Timer.cpp.i

lib/Timer/Timer.s: lib/Timer/Timer.cpp.s

.PHONY : lib/Timer/Timer.s

# target to generate assembly for a file
lib/Timer/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/Timer/Timer.cpp.s
.PHONY : lib/Timer/Timer.cpp.s

lib/aeronautics/aeronautics.o: lib/aeronautics/aeronautics.cpp.o

.PHONY : lib/aeronautics/aeronautics.o

# target to build an object file
lib/aeronautics/aeronautics.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/aeronautics/aeronautics.cpp.o
.PHONY : lib/aeronautics/aeronautics.cpp.o

lib/aeronautics/aeronautics.i: lib/aeronautics/aeronautics.cpp.i

.PHONY : lib/aeronautics/aeronautics.i

# target to preprocess a source file
lib/aeronautics/aeronautics.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/aeronautics/aeronautics.cpp.i
.PHONY : lib/aeronautics/aeronautics.cpp.i

lib/aeronautics/aeronautics.s: lib/aeronautics/aeronautics.cpp.s

.PHONY : lib/aeronautics/aeronautics.s

# target to generate assembly for a file
lib/aeronautics/aeronautics.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/aeronautics/aeronautics.cpp.s
.PHONY : lib/aeronautics/aeronautics.cpp.s

lib/analog/analogBase.o: lib/analog/analogBase.cpp.o

.PHONY : lib/analog/analogBase.o

# target to build an object file
lib/analog/analogBase.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/analog/analogBase.cpp.o
.PHONY : lib/analog/analogBase.cpp.o

lib/analog/analogBase.i: lib/analog/analogBase.cpp.i

.PHONY : lib/analog/analogBase.i

# target to preprocess a source file
lib/analog/analogBase.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/analog/analogBase.cpp.i
.PHONY : lib/analog/analogBase.cpp.i

lib/analog/analogBase.s: lib/analog/analogBase.cpp.s

.PHONY : lib/analog/analogBase.s

# target to generate assembly for a file
lib/analog/analogBase.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/analog/analogBase.cpp.s
.PHONY : lib/analog/analogBase.cpp.s

lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.o: lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.o

.PHONY : lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.o

# target to build an object file
lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.o
.PHONY : lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.o

lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.i: lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.i

.PHONY : lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.i

# target to preprocess a source file
lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.i
.PHONY : lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.i

lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.s: lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.s

.PHONY : lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.s

# target to generate assembly for a file
lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.s
.PHONY : lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.cpp.s

lib/analog/overlays/analogOverlay.o: lib/analog/overlays/analogOverlay.cpp.o

.PHONY : lib/analog/overlays/analogOverlay.o

# target to build an object file
lib/analog/overlays/analogOverlay.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/analog/overlays/analogOverlay.cpp.o
.PHONY : lib/analog/overlays/analogOverlay.cpp.o

lib/analog/overlays/analogOverlay.i: lib/analog/overlays/analogOverlay.cpp.i

.PHONY : lib/analog/overlays/analogOverlay.i

# target to preprocess a source file
lib/analog/overlays/analogOverlay.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/analog/overlays/analogOverlay.cpp.i
.PHONY : lib/analog/overlays/analogOverlay.cpp.i

lib/analog/overlays/analogOverlay.s: lib/analog/overlays/analogOverlay.cpp.s

.PHONY : lib/analog/overlays/analogOverlay.s

# target to generate assembly for a file
lib/analog/overlays/analogOverlay.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/analog/overlays/analogOverlay.cpp.s
.PHONY : lib/analog/overlays/analogOverlay.cpp.s

lib/external/PID.o: lib/external/PID.cpp.o

.PHONY : lib/external/PID.o

# target to build an object file
lib/external/PID.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/external/PID.cpp.o
.PHONY : lib/external/PID.cpp.o

lib/external/PID.i: lib/external/PID.cpp.i

.PHONY : lib/external/PID.i

# target to preprocess a source file
lib/external/PID.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/external/PID.cpp.i
.PHONY : lib/external/PID.cpp.i

lib/external/PID.s: lib/external/PID.cpp.s

.PHONY : lib/external/PID.s

# target to generate assembly for a file
lib/external/PID.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/external/PID.cpp.s
.PHONY : lib/external/PID.cpp.s

lib/i2c/devices/L3GD20H/L3GD20H.o: lib/i2c/devices/L3GD20H/L3GD20H.cpp.o

.PHONY : lib/i2c/devices/L3GD20H/L3GD20H.o

# target to build an object file
lib/i2c/devices/L3GD20H/L3GD20H.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/L3GD20H/L3GD20H.cpp.o
.PHONY : lib/i2c/devices/L3GD20H/L3GD20H.cpp.o

lib/i2c/devices/L3GD20H/L3GD20H.i: lib/i2c/devices/L3GD20H/L3GD20H.cpp.i

.PHONY : lib/i2c/devices/L3GD20H/L3GD20H.i

# target to preprocess a source file
lib/i2c/devices/L3GD20H/L3GD20H.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/L3GD20H/L3GD20H.cpp.i
.PHONY : lib/i2c/devices/L3GD20H/L3GD20H.cpp.i

lib/i2c/devices/L3GD20H/L3GD20H.s: lib/i2c/devices/L3GD20H/L3GD20H.cpp.s

.PHONY : lib/i2c/devices/L3GD20H/L3GD20H.s

# target to generate assembly for a file
lib/i2c/devices/L3GD20H/L3GD20H.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/L3GD20H/L3GD20H.cpp.s
.PHONY : lib/i2c/devices/L3GD20H/L3GD20H.cpp.s

lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.o: lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.o

.PHONY : lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.o

# target to build an object file
lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.o
.PHONY : lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.o

lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.i: lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.i

.PHONY : lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.i

# target to preprocess a source file
lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.i
.PHONY : lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.i

lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.s: lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.s

.PHONY : lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.s

# target to generate assembly for a file
lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.s
.PHONY : lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.cpp.s

lib/i2c/devices/LSM303/LSM303DLHC.o: lib/i2c/devices/LSM303/LSM303DLHC.cpp.o

.PHONY : lib/i2c/devices/LSM303/LSM303DLHC.o

# target to build an object file
lib/i2c/devices/LSM303/LSM303DLHC.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/LSM303/LSM303DLHC.cpp.o
.PHONY : lib/i2c/devices/LSM303/LSM303DLHC.cpp.o

lib/i2c/devices/LSM303/LSM303DLHC.i: lib/i2c/devices/LSM303/LSM303DLHC.cpp.i

.PHONY : lib/i2c/devices/LSM303/LSM303DLHC.i

# target to preprocess a source file
lib/i2c/devices/LSM303/LSM303DLHC.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/LSM303/LSM303DLHC.cpp.i
.PHONY : lib/i2c/devices/LSM303/LSM303DLHC.cpp.i

lib/i2c/devices/LSM303/LSM303DLHC.s: lib/i2c/devices/LSM303/LSM303DLHC.cpp.s

.PHONY : lib/i2c/devices/LSM303/LSM303DLHC.s

# target to generate assembly for a file
lib/i2c/devices/LSM303/LSM303DLHC.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/LSM303/LSM303DLHC.cpp.s
.PHONY : lib/i2c/devices/LSM303/LSM303DLHC.cpp.s

lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.o: lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.o

.PHONY : lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.o

# target to build an object file
lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.o
.PHONY : lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.o

lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.i: lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.i

.PHONY : lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.i

# target to preprocess a source file
lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.i
.PHONY : lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.i

lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.s: lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.s

.PHONY : lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.s

# target to generate assembly for a file
lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.s
.PHONY : lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.cpp.s

lib/i2c/i2cDevice.o: lib/i2c/i2cDevice.cpp.o

.PHONY : lib/i2c/i2cDevice.o

# target to build an object file
lib/i2c/i2cDevice.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/i2cDevice.cpp.o
.PHONY : lib/i2c/i2cDevice.cpp.o

lib/i2c/i2cDevice.i: lib/i2c/i2cDevice.cpp.i

.PHONY : lib/i2c/i2cDevice.i

# target to preprocess a source file
lib/i2c/i2cDevice.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/i2cDevice.cpp.i
.PHONY : lib/i2c/i2cDevice.cpp.i

lib/i2c/i2cDevice.s: lib/i2c/i2cDevice.cpp.s

.PHONY : lib/i2c/i2cDevice.s

# target to generate assembly for a file
lib/i2c/i2cDevice.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/i2c/i2cDevice.cpp.s
.PHONY : lib/i2c/i2cDevice.cpp.s

lib/orientation/orientation.o: lib/orientation/orientation.cpp.o

.PHONY : lib/orientation/orientation.o

# target to build an object file
lib/orientation/orientation.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/orientation/orientation.cpp.o
.PHONY : lib/orientation/orientation.cpp.o

lib/orientation/orientation.i: lib/orientation/orientation.cpp.i

.PHONY : lib/orientation/orientation.i

# target to preprocess a source file
lib/orientation/orientation.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/orientation/orientation.cpp.i
.PHONY : lib/orientation/orientation.cpp.i

lib/orientation/orientation.s: lib/orientation/orientation.cpp.s

.PHONY : lib/orientation/orientation.s

# target to generate assembly for a file
lib/orientation/orientation.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/orientation/orientation.cpp.s
.PHONY : lib/orientation/orientation.cpp.s

lib/overlays/overlayBase.o: lib/overlays/overlayBase.cpp.o

.PHONY : lib/overlays/overlayBase.o

# target to build an object file
lib/overlays/overlayBase.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/overlays/overlayBase.cpp.o
.PHONY : lib/overlays/overlayBase.cpp.o

lib/overlays/overlayBase.i: lib/overlays/overlayBase.cpp.i

.PHONY : lib/overlays/overlayBase.i

# target to preprocess a source file
lib/overlays/overlayBase.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/overlays/overlayBase.cpp.i
.PHONY : lib/overlays/overlayBase.cpp.i

lib/overlays/overlayBase.s: lib/overlays/overlayBase.cpp.s

.PHONY : lib/overlays/overlayBase.s

# target to generate assembly for a file
lib/overlays/overlayBase.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/overlays/overlayBase.cpp.s
.PHONY : lib/overlays/overlayBase.cpp.s

lib/overlays/pinOverlay.o: lib/overlays/pinOverlay.cpp.o

.PHONY : lib/overlays/pinOverlay.o

# target to build an object file
lib/overlays/pinOverlay.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/overlays/pinOverlay.cpp.o
.PHONY : lib/overlays/pinOverlay.cpp.o

lib/overlays/pinOverlay.i: lib/overlays/pinOverlay.cpp.i

.PHONY : lib/overlays/pinOverlay.i

# target to preprocess a source file
lib/overlays/pinOverlay.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/overlays/pinOverlay.cpp.i
.PHONY : lib/overlays/pinOverlay.cpp.i

lib/overlays/pinOverlay.s: lib/overlays/pinOverlay.cpp.s

.PHONY : lib/overlays/pinOverlay.s

# target to generate assembly for a file
lib/overlays/pinOverlay.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/overlays/pinOverlay.cpp.s
.PHONY : lib/overlays/pinOverlay.cpp.s

lib/pwm/motors/dji_2212/dji_2212.o: lib/pwm/motors/dji_2212/dji_2212.cpp.o

.PHONY : lib/pwm/motors/dji_2212/dji_2212.o

# target to build an object file
lib/pwm/motors/dji_2212/dji_2212.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/motors/dji_2212/dji_2212.cpp.o
.PHONY : lib/pwm/motors/dji_2212/dji_2212.cpp.o

lib/pwm/motors/dji_2212/dji_2212.i: lib/pwm/motors/dji_2212/dji_2212.cpp.i

.PHONY : lib/pwm/motors/dji_2212/dji_2212.i

# target to preprocess a source file
lib/pwm/motors/dji_2212/dji_2212.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/motors/dji_2212/dji_2212.cpp.i
.PHONY : lib/pwm/motors/dji_2212/dji_2212.cpp.i

lib/pwm/motors/dji_2212/dji_2212.s: lib/pwm/motors/dji_2212/dji_2212.cpp.s

.PHONY : lib/pwm/motors/dji_2212/dji_2212.s

# target to generate assembly for a file
lib/pwm/motors/dji_2212/dji_2212.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/motors/dji_2212/dji_2212.cpp.s
.PHONY : lib/pwm/motors/dji_2212/dji_2212.cpp.s

lib/pwm/motors/motors.o: lib/pwm/motors/motors.cpp.o

.PHONY : lib/pwm/motors/motors.o

# target to build an object file
lib/pwm/motors/motors.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/motors/motors.cpp.o
.PHONY : lib/pwm/motors/motors.cpp.o

lib/pwm/motors/motors.i: lib/pwm/motors/motors.cpp.i

.PHONY : lib/pwm/motors/motors.i

# target to preprocess a source file
lib/pwm/motors/motors.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/motors/motors.cpp.i
.PHONY : lib/pwm/motors/motors.cpp.i

lib/pwm/motors/motors.s: lib/pwm/motors/motors.cpp.s

.PHONY : lib/pwm/motors/motors.s

# target to generate assembly for a file
lib/pwm/motors/motors.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/motors/motors.cpp.s
.PHONY : lib/pwm/motors/motors.cpp.s

lib/pwm/overlays/pwmOverlay.o: lib/pwm/overlays/pwmOverlay.cpp.o

.PHONY : lib/pwm/overlays/pwmOverlay.o

# target to build an object file
lib/pwm/overlays/pwmOverlay.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/overlays/pwmOverlay.cpp.o
.PHONY : lib/pwm/overlays/pwmOverlay.cpp.o

lib/pwm/overlays/pwmOverlay.i: lib/pwm/overlays/pwmOverlay.cpp.i

.PHONY : lib/pwm/overlays/pwmOverlay.i

# target to preprocess a source file
lib/pwm/overlays/pwmOverlay.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/overlays/pwmOverlay.cpp.i
.PHONY : lib/pwm/overlays/pwmOverlay.cpp.i

lib/pwm/overlays/pwmOverlay.s: lib/pwm/overlays/pwmOverlay.cpp.s

.PHONY : lib/pwm/overlays/pwmOverlay.s

# target to generate assembly for a file
lib/pwm/overlays/pwmOverlay.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/overlays/pwmOverlay.cpp.s
.PHONY : lib/pwm/overlays/pwmOverlay.cpp.s

lib/pwm/pwmDevice.o: lib/pwm/pwmDevice.cpp.o

.PHONY : lib/pwm/pwmDevice.o

# target to build an object file
lib/pwm/pwmDevice.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/pwmDevice.cpp.o
.PHONY : lib/pwm/pwmDevice.cpp.o

lib/pwm/pwmDevice.i: lib/pwm/pwmDevice.cpp.i

.PHONY : lib/pwm/pwmDevice.i

# target to preprocess a source file
lib/pwm/pwmDevice.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/pwmDevice.cpp.i
.PHONY : lib/pwm/pwmDevice.cpp.i

lib/pwm/pwmDevice.s: lib/pwm/pwmDevice.cpp.s

.PHONY : lib/pwm/pwmDevice.s

# target to generate assembly for a file
lib/pwm/pwmDevice.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/lib/pwm/pwmDevice.cpp.s
.PHONY : lib/pwm/pwmDevice.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/main.cpp.s
.PHONY : main.cpp.s

quadroCopter.o: quadroCopter.cpp.o

.PHONY : quadroCopter.o

# target to build an object file
quadroCopter.cpp.o:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/quadroCopter.cpp.o
.PHONY : quadroCopter.cpp.o

quadroCopter.i: quadroCopter.cpp.i

.PHONY : quadroCopter.i

# target to preprocess a source file
quadroCopter.cpp.i:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/quadroCopter.cpp.i
.PHONY : quadroCopter.cpp.i

quadroCopter.s: quadroCopter.cpp.s

.PHONY : quadroCopter.s

# target to generate assembly for a file
quadroCopter.cpp.s:
	$(MAKE) -f CMakeFiles/Quadro.dir/build.make CMakeFiles/Quadro.dir/quadroCopter.cpp.s
.PHONY : quadroCopter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Quadro"
	@echo "... lib/Timer/Timer.o"
	@echo "... lib/Timer/Timer.i"
	@echo "... lib/Timer/Timer.s"
	@echo "... lib/aeronautics/aeronautics.o"
	@echo "... lib/aeronautics/aeronautics.i"
	@echo "... lib/aeronautics/aeronautics.s"
	@echo "... lib/analog/analogBase.o"
	@echo "... lib/analog/analogBase.i"
	@echo "... lib/analog/analogBase.s"
	@echo "... lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.o"
	@echo "... lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.i"
	@echo "... lib/analog/devices/LVMaxSonarEZ/LVMaxSonarEZ.s"
	@echo "... lib/analog/overlays/analogOverlay.o"
	@echo "... lib/analog/overlays/analogOverlay.i"
	@echo "... lib/analog/overlays/analogOverlay.s"
	@echo "... lib/external/PID.o"
	@echo "... lib/external/PID.i"
	@echo "... lib/external/PID.s"
	@echo "... lib/i2c/devices/L3GD20H/L3GD20H.o"
	@echo "... lib/i2c/devices/L3GD20H/L3GD20H.i"
	@echo "... lib/i2c/devices/L3GD20H/L3GD20H.s"
	@echo "... lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.o"
	@echo "... lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.i"
	@echo "... lib/i2c/devices/LSM303/Accelerometer/LSM303Accelerometer.s"
	@echo "... lib/i2c/devices/LSM303/LSM303DLHC.o"
	@echo "... lib/i2c/devices/LSM303/LSM303DLHC.i"
	@echo "... lib/i2c/devices/LSM303/LSM303DLHC.s"
	@echo "... lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.o"
	@echo "... lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.i"
	@echo "... lib/i2c/devices/LSM303/Magnetometer/LSM303Magnetometer.s"
	@echo "... lib/i2c/i2cDevice.o"
	@echo "... lib/i2c/i2cDevice.i"
	@echo "... lib/i2c/i2cDevice.s"
	@echo "... lib/orientation/orientation.o"
	@echo "... lib/orientation/orientation.i"
	@echo "... lib/orientation/orientation.s"
	@echo "... lib/overlays/overlayBase.o"
	@echo "... lib/overlays/overlayBase.i"
	@echo "... lib/overlays/overlayBase.s"
	@echo "... lib/overlays/pinOverlay.o"
	@echo "... lib/overlays/pinOverlay.i"
	@echo "... lib/overlays/pinOverlay.s"
	@echo "... lib/pwm/motors/dji_2212/dji_2212.o"
	@echo "... lib/pwm/motors/dji_2212/dji_2212.i"
	@echo "... lib/pwm/motors/dji_2212/dji_2212.s"
	@echo "... lib/pwm/motors/motors.o"
	@echo "... lib/pwm/motors/motors.i"
	@echo "... lib/pwm/motors/motors.s"
	@echo "... lib/pwm/overlays/pwmOverlay.o"
	@echo "... lib/pwm/overlays/pwmOverlay.i"
	@echo "... lib/pwm/overlays/pwmOverlay.s"
	@echo "... lib/pwm/pwmDevice.o"
	@echo "... lib/pwm/pwmDevice.i"
	@echo "... lib/pwm/pwmDevice.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... quadroCopter.o"
	@echo "... quadroCopter.i"
	@echo "... quadroCopter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

